export const TYPE_VARINT = 0;
export const TYPE_I64 = 1;
export const TYPE_LEN = 2;
// Not supported: SGROUP 3, EGROUP 4
export const TYPE_I32 = 5;

export const FIELD_SIZE_UNKNOWN = 0;
export const FIELD_SIZE_32 = 1 << 0;
export const FIELD_SIZE_64 = 1 << 1;
export const FIELD_SIZE_FIXED_32 = 1 << 2;
export const FIELD_SIZE_FIXED_64 = 1 << 3;

export const FIELD_SIZE_MASK =
  FIELD_SIZE_UNKNOWN |
  FIELD_SIZE_32 |
  FIELD_SIZE_64 |
  FIELD_SIZE_FIXED_32 |
  FIELD_SIZE_FIXED_64;

export const FIELD_ENC_UNKNOWN = 0;
export const FIELD_ENC_SIGNED = 1 << 4;
export const FIELD_ENC_UNSIGNED = 1 << 5;
export const FIELD_ENC_RSIGNED = 1 << 6; // First bit is a sign
export const FIELD_ENC_BOOL = 1 << 7;
export const FIELD_ENC_IEEE754 = 1 << 8;
export const FIELD_ENC_BYTES = 1 << 9;
export const FIELD_ENC_STRING = 1 << 10;
export const FIELD_ENC_MESSAGE = 1 << 11;

// Just to keep `FIELD_ENUM` different from uint32
const FIELD_NESTED = 1 << 12;

export const FIELD_ENC_MASK =
  FIELD_ENC_UNKNOWN |
  FIELD_ENC_SIGNED |
  FIELD_ENC_UNSIGNED |
  FIELD_ENC_RSIGNED |
  FIELD_ENC_BOOL |
  FIELD_ENC_IEEE754 |
  FIELD_ENC_BYTES |
  FIELD_ENC_STRING |
  FIELD_ENC_MESSAGE;

// Absent field

export const FIELD_UNKNOWN = FIELD_SIZE_UNKNOWN | FIELD_ENC_UNKNOWN;

// VARINT

export const FIELD_INT32 = FIELD_SIZE_32 | FIELD_ENC_SIGNED;
export const FIELD_UINT32 = FIELD_SIZE_32 | FIELD_ENC_UNSIGNED;
export const FIELD_SINT32 = FIELD_SIZE_32 | FIELD_ENC_RSIGNED;
export const FIELD_INT64 = FIELD_SIZE_64 | FIELD_ENC_SIGNED;
export const FIELD_UINT64 = FIELD_SIZE_64 | FIELD_ENC_UNSIGNED;
export const FIELD_SINT64 = FIELD_SIZE_64 | FIELD_ENC_RSIGNED;
export const FIELD_BOOL = FIELD_SIZE_32 | FIELD_ENC_BOOL;
export const FIELD_ENUM = FIELD_UINT32 | FIELD_NESTED;

// I32

export const FIELD_FIXED32 = FIELD_SIZE_FIXED_32 | FIELD_ENC_UNSIGNED;
export const FIELD_SFIXED32 = FIELD_SIZE_FIXED_32 | FIELD_ENC_SIGNED;
export const FIELD_FLOAT = FIELD_SIZE_FIXED_32 | FIELD_ENC_IEEE754;

// I64

export const FIELD_FIXED64 = FIELD_SIZE_FIXED_64 | FIELD_ENC_UNSIGNED;
export const FIELD_SFIXED64 = FIELD_SIZE_FIXED_64 | FIELD_ENC_SIGNED;
export const FIELD_DOUBLE = FIELD_SIZE_FIXED_64 | FIELD_ENC_IEEE754;

// LEN

export const FIELD_STRING = FIELD_SIZE_UNKNOWN | FIELD_ENC_STRING;
export const FIELD_BYTES = FIELD_SIZE_UNKNOWN | FIELD_ENC_BYTES;
export const FIELD_MESSAGE = FIELD_SIZE_UNKNOWN | FIELD_ENC_MESSAGE;
